### ISSUE TITLE
Eclipse version to use

### ISSUE THREAD

**Issue by RobertDiebels** [akhikhl/wuff#12]
How and where do I set the version of the Eclipse framework I want to use?
By default Luna is used. But my source depends on 3.7. Where do I configure Wuff to use that instead? 
The wiki doesn't elaborate on this :).

**Comment by rkhalily** [comment]
Hi

i also get errors when change source property for using  a local eclipse source.
"Colud not find method wuff for arguments [build...] on root project.

**Comment by pradip-maharjan** [comment]
Even I selected ecllipse as 4.6, the wuff is trying to download from http://mirror.netcologne.de/eclipse//eclipse/downloads/drops4/R-4.5-201506032000/eclipse-SDK-4.5-linux-gtk-x86_64.tar.gz
which is not available at eclipse site. How to get out of this?

**Comment by RobertDiebels** [comment]
@akhikhl so so sorry for the non-responsiveness. I worked on this in some free coding time at a former employer. Totally forgot about it. I have no idea what my setup was back then, so I can't reproduce this. I'll close it so you don't have to worry about it anymore.

Again, so sorry.
