### ISSUE TITLE
Remove 'Require-Bundle: org.eclipse.osgi'

### ISSUE THREAD

**Issue by brunobasto** [akhikhl/wuff#66]
Hello, I'm using the ``apply plugin: 'org.akhikhl.wuff.osgi-bundle'`` plugin to deploy a bundle to [Apache Karaf](http://karaf.apache.org/index.html) and I'm almost sure I don't need the dependency on org.eclipse.osgi. But whenever I build a bundle, that header is added. Is there a way to remove that header from my manifest?

Thx

**Comment by akhikhl** [comment]
I tried removing org.eclipse.osgi dependency - it worked. I'll see to removing this dependency in the next version of Wuff.

**Comment by brunobasto** [comment]
Awesome! Thanks for the quick response. In the mean time, is there something I can put in my ``build.gradle`` to solve the issue temporarily?

Thx again

**Comment by akhikhl** [comment]
You can use snapshot version, it contains the fix:

```groovy
buildscript {
  repositories {
    jcenter()
    maven { url 'http://oss.jfrog.org/artifactory/oss-snapshot-local' }
  }

  dependencies {
    classpath 'org.akhikhl.wuff:wuff-plugin:0.0.14-SNAPSHOT'
  }
}

repositories {
  jcenter()
  maven { url 'http://oss.jfrog.org/artifactory/oss-snapshot-local' }
}

apply plugin: 'java'
apply plugin: 'org.akhikhl.wuff.eclipse-rcp-app'
```

New release comes today or tomorrow, depending on bug-fixing/tests.

**Comment by brunobasto** [comment]
Awesome! Thank you very much.
