### ISSUE TITLE
Bundle-ActivationPolicy: lazy

### ISSUE THREAD

**Issue by brunobasto** [akhikhl/wuff#67]
Is there a way choose if the header `Bundle-ActivationPolicy: lazy` will be included in the manifest or not? Some times I want my bundles to start right away. Would be a nice thing to have.

P.S.: Wuff is an amazing plugin :) Thanks

**Comment by akhikhl** [comment]
I'll see to introducing control over this.

**Comment by brunobasto** [comment]
Thank you
