### ISSUE TITLE
Do the examples really work?

### ISSUE THREAD

**Issue by romu70** [akhikhl/wuff#92]
Hi,
I'm trying to figure out how Wuff works and how I can use it for my company build system. I've a very small knowledge of Wuff. So, I think building the examples could be a good way to start learning Wuff.

If I run the following command from the wuff folder: 
```
./gradlew -b examples/PluginXml-1/MyEclipsePlugin/build.gradle
```

I get the ```BUILD SUCCESSFULL``` message, great! But what's not great is nothing has been really built. In the ```build``` folder I only get a ```maven-ant-tasks-2.1.4-SNAPSHOT.jar``` which is obviously not the plugin I'm trying to build.

I've tried with other examples from the ones provided, and that's the same. Any idea?

**Comment by mcmil** [comment]
I think you've missed the task name (`build`) in the gradle call. Try:

````
./gradlew -b examples/PluginXml-1/MyEclipsePlugin/build.gradle build
````

You should see the output in `wuff-0.0.18\examples\PluginXml-1\MyEclipsePlugin\build`

**Comment by romu70** [comment]
Obviously! How stupid I can be!! Thankd for the help.
