### ISSUE TITLE
Wrong extension point generation in plugin.xml

### ISSUE THREAD

**Issue by petarov** [akhikhl/wuff#95]
Hi,

I've got a weird behavior that I think comes down to [this line](https://github.com/akhikhl/wuff/blob/68c1c86a2ac7fef341bad97c4c08eb5d2c77a1c6/libs/wuff-plugin/src/main/groovy/org/akhikhl/wuff/EclipseBundlePluginXmlBuilder.groovy#L54) in [EclipseBundlePluginXmlBuilder](https://github.com/akhikhl/wuff/blob/68c1c86a2ac7fef341bad97c4c08eb5d2c77a1c6/libs/wuff-plugin/src/main/groovy/org/akhikhl/wuff/EclipseBundlePluginXmlBuilder.groovy). I have a java class named `ViewLogin` that has a completely different purpose than being an Eclipse extension point, however, after building my project I get the following in the plugin.xml file:

``` xml
  <extension point="org.eclipse.ui.views">
    <view id="com.mycompany.ViewLogin" n
    ame="com.mycompany ViewLogin" 
    class="com.mycompany.ui.ViewLogin"/>
  </extension>
```

I will patch it in my own fork, but I was wondering what is the idea behind this extension point generation? Could it be removed in the future?

**Comment by muenzpraeger** [comment]
The extension point generation is part of the built-in auto-detection of "View" classes that conform to the following specification.

'**/*View.groovy', '**/_View.java', '__/View_.groovy', '*_/View_.java'

See also here: https://github.com/akhikhl/wuff/wiki/plugin.xml-for-eclipse-bundle
